version: "3"
services:
    proxy:
        image: nginx:mainline-alpine
        ports:
            - 80:80
            - 443:443
        volumes:
            - www-vol:/var/www/html:cached
            - ./conf/nginx/:/etc/nginx/conf.d/
            - certs-vol:/certs:ro
        environment:
            - HOST_NAME=${HOST_NAME}
        command: /bin/sh -c "envsubst < /etc/nginx/conf.d/templates/server_name.template > /etc/nginx/conf.d/server_name.active && nginx -g 'daemon off;'"
        networks:
            - backend
        restart: always

    acme:
        build: ./Dockerfiles/acme
        volumes:
            - certs-vol:/certs
            - ./Dockerfiles/acme/run.sh:/run.sh
            - ./Dockerfiles/acme/updatecert:/etc/periodic/daily/updatecert
            - /var/run/docker.sock:/var/run/docker.sock
            - www-vol:/var/www:cached
            - ./Dockerfiles/acme/ssl-example:/dummyssl
        restart: always
        entrypoint: ""
        command: /bin/sh -c 'chmod +x /run.sh && chmod 0744 /etc/periodic/daily/updatecert && crond -f'
        environment:
            - HOST_NAME=${HOST_NAME}    # used for self signed certificate
            - LETSENCRYPT_DOMAINS=${LETSENCRYPT_DOMAINS}
            - EMAIL=${EMAIL}
            - DOCKER_API_VERSION=${DOCKER_API_VERSION}
            - SELF_SIGNED=${SELF_SIGNED}
            - LETSENCRYPT=${LETSENCRYPT}
            - TZ=${TZ}
        networks:
            - backend
    
networks:
    backend:
        driver: bridge
       
volumes:
    certs-vol:
    www-vol:
